package main;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gurev' at '10/31/16 9:18 AM' with Gradle 2.14.1
 *
 * @author gurev, @date 10/31/16 9:18 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
